//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HseDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9DE66D_beaconsEntities : DbContext
    {
        public DB_9DE66D_beaconsEntities()
            : base("name=DB_9DE66D_beaconsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<new_arcs> new_arcs { get; set; }
        public virtual DbSet<new_builds> new_builds { get; set; }
        public virtual DbSet<new_connection> new_connection { get; set; }
        public virtual DbSet<new_floors> new_floors { get; set; }
        public virtual DbSet<new_ibeacons> new_ibeacons { get; set; }
        public virtual DbSet<new_nodes> new_nodes { get; set; }
    }
}
