//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_ibeacons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public new_ibeacons()
        {
            this.new_nodes = new HashSet<new_nodes>();
        }
    
        public int beaconId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string uuid { get; set; }
        public int minor { get; set; }
        public int major { get; set; }
        public Nullable<int> mapIdFK { get; set; }
        public Nullable<int> coordX { get; set; }
        public Nullable<int> coordY { get; set; }
        public Nullable<int> nodeNum { get; set; }
        public Nullable<int> batteryLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<new_nodes> new_nodes { get; set; }
    }
}
