//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_builds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public new_builds()
        {
            this.new_floors = new HashSet<new_floors>();
        }
    
        public int buildingId { get; set; }
        public string buildingName { get; set; }
        public string buildingNameRu { get; set; }
        public string matrixFile { get; set; }
        public string imageFile { get; set; }
        public string description { get; set; }
        public Nullable<decimal> latt { get; set; }
        public Nullable<decimal> longt { get; set; }
        public string city { get; set; }
        public string street { get; set; }
        public string house { get; set; }
        public string country { get; set; }
        public Nullable<decimal> compass { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<new_floors> new_floors { get; set; }
    }
}
