//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_connection
    {
        public int connectionId { get; set; }
        public Nullable<int> nodeFrst { get; set; }
        public Nullable<int> nodeScnd { get; set; }
        public Nullable<int> arcIdFk { get; set; }
    
        public virtual new_arcs new_arcs { get; set; }
        public virtual new_nodes new_nodes { get; set; }
        public virtual new_nodes new_nodes1 { get; set; }
    }
}
