//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HseDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_floors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public new_floors()
        {
            this.new_nodes = new HashSet<new_nodes>();
        }
    
        public int floorId { get; set; }
        public string dir { get; set; }
        public string tiles { get; set; }
        public Nullable<int> tilesXcount { get; set; }
        public Nullable<int> tilesYcount { get; set; }
        public string mapLevel { get; set; }
        public Nullable<int> buildingIdFk { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
    
        public virtual new_builds new_builds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<new_nodes> new_nodes { get; set; }
    }
}
